# Generated by Django 2.2.7 on 2020-03-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('place_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='case',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aware.Location'),
        ),
    ]
