# Generated by Django 2.2.7 on 2020-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aware', '0002_auto_20200331_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='category',
            new_name='case_type',
        ),
    ]
