# Generated by Django 2.2.7 on 2020-04-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aware', '0005_auto_20200331_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Aware.Location'),
        ),
    ]
