# Generated by Django 2.2.7 on 2020-04-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aware', '0006_auto_20200402_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aware.Location'),
        ),
    ]
