# Generated by Django 2.2.7 on 2020-04-04 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aware', '0008_case_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-case_type']},
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Case', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('user', 'address')},
        ),
    ]
